// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlickityController from "./flickity_controller"
application.register("flickity", FlickityController)

import GalleryCardController from "./gallery_card_controller"
application.register("gallery-card", GalleryCardController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LogoController from "./logo_controller"
application.register("logo", LogoController)

import ProfileCardController from "./profile_card_controller"
application.register("profile-card", ProfileCardController)

import ProfileModalController from "./profile_modal_controller"
application.register("profile-modal", ProfileModalController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import TimeZoneController from "./time_zone_controller"
application.register("time-zone", TimeZoneController)
