// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GalleryCardController from "./gallery_card_controller"
application.register("gallery-card", GalleryCardController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LogoController from "./logo_controller"
application.register("logo", LogoController)
