meta_name: "SoundState"
meta_title: "SoundState - Your Audio Fingerprint"
meta_description: "Music for the Eyes - Transforming Music into Image with AI"
meta_image: "logo.png" # should exist in `app/assets/images/`
