meta_name: "SoundState"
meta_title: "SoundState - Your Audio Fingerprint"
meta_description: "See Your Music in a New Light - Transforming Music into Art with AI"
meta_image: "logo.png" # should exist in `app/assets/images/`
